### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by specialTT** [anviaan/ElectricMace#6]
### What happened?

The mod file cannot be found. Even if I search for "mace", I cannot find the file. What is the name of this mod?
The main reason I'm uninstalling it is that I still have issue #4 while using it, and the "Surge Protector" advancement that triggers during thunder.

### Loader

fabric

### Mod Version

1.4

### Minecraft Version

1.21

**Comment by anviaan** [comment]
The mod file name is ElectricMace-fabric-1.21-1.4.jar

**Comment by specialTT** [comment]
I was looking for it using this name, but couldn't find it.
